debug: false
# Server Configuration
server:
  port: 8081

# Spring Configuration
spring:
  application:
    name: jad-admin
  #  profiles:
  #    active: dev # 环境设置：dev、test、prod
  datasource:
    url: jdbc:mysql://localhost:3306/dev_jad_admin?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=true&allowMultiQueries=true&autoReconnect=true&useAffectRows=true
    username: root
    password: cxxwl96@sina.com
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-wait-millis: 10000
      initial-size: 5
  redis:
    host: localhost
    port: 6379
    password: cxxwl96@sina.com
    database: 0
    timeout: 3000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 返回json的全局时间格式
    time-zone: GMT+8 # 时区
  devtools:
    restart:
      enabled: true # 设置开启热部署
  freemarker:
    cache: false # 页面不加载缓存，修改即时生效

# MyBatisPlus Configuration
mybatis-plus:
  mapper-locations: classpath*:com/jad/**/mapper/xml/*.xml # 配置mapper xml文件的路径
  type-aliases-package: com.jad.**.mapper
  type-enums-package: com.jad.**.enums # 枚举转换
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler # 使用ordinal处理枚举转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis日志

# JAD Configuration
jad:
  jwt:
    expire-milliseconds: 86400000 # 过期时间（单位：ms）
    secret: cxxwl96 # jwt秘钥
    header: Authorization
  security:
    url-white-list: /auth/captcha/generator,/test/**,/cxx
  system:
    auth-config:
      captcha-timeout: 120 # 验证码过期时间（单位：s）
    info:
      app-name: JADAdmin
      version: 1.0.0
      uri: jad.com
      email: cxxwl96@sina.com
    role:
      administrator-id: 8288e8e0fc49ec42a6d83d121963af57 # 超级管理员
  swagger:
    enable: true
    path-mapping: /
    api-info:
      title: JAD Admin Swagger API
      description: JAD 相关接口
      version: 1.0.0
      contact:
        name: cxxwl96
        url: ""
        email: "cxxwl96@sina.com"
      license: ""
      license-url: ""
